### ISSUE TITLE
「评论」Flex上手与实战

### ISSUE THREAD

**Issue by dongyuanxin** [dongyuanxin/blog#60]
Flex上手与实战：https://xin-tan.com/passages/2019-04-09-es6/

**Comment by git710** [comment]
水平垂直居中的代码挂了

**Comment by dongyuanxin** [comment]
> @git710  水平垂直居中的代码挂了

```css
div {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

谢谢提醒，已经补上了
